### ISSUE TITLE
0.6.1 not work

### ISSUE THREAD

**Issue by kilinbox** [norihiro/obs-face-tracker#112]
used OBS 28.0-rc1(arm64).
Do I need to install libopenblas.dylib?

error log
> 08:00:11.717: Module '/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker' not loaded
> 08:00:11.971: os_dlopen(/Users/user/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker->/Users/user/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker): dlopen(/Users/user/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker, 0x0101): Library not loaded: '/usr/local/opt/arm64/lib/libopenblas.dylib'
> 08:00:11.971:   Referenced from: '/Users/user/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker'
> 08:00:11.971:   Reason: tried: '/usr/local/opt/arm64/lib/libopenblas.dylib' (no such file), '/usr/lib/libopenblas.dylib' (no such file)
> 08:00:11.971: 
> 08:00:11.971: Module '/Users/user/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker' not loaded

0.6.0 didn't have this issue.
It seems that there is a difference in the dependent libraries.

0.6.0(arm64)
otool -L obs-face-tracker/bin/obs-face-tracker.so

> 	@rpath/libobs-frontend-api.1.dylib (compatibility version 1.0.0, current version 28.0.0)
> 	@rpath/libobs.framework/Versions/A/libobs (compatibility version 1.0.0, current version 28.0.0)
> 	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

0.6.1(arm64)
otool -L obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker 

> 	@rpath/libobs-frontend-api.1.dylib (compatibility version 1.0.0, current version 28.0.0)
> 	@rpath/libobs.framework/Versions/A/libobs (compatibility version 1.0.0, current version 28.0.0)
> 	/usr/local/opt/openblas/lib/libopenblas.0.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)

thanks.

**Comment by norihiro** [comment]
Thank you for your report.
I tried to add `libopenblas.dylib` as same as x86_64 architecture. The file `libopenblas.dylib` is supposed to be included in the package.
It looks like there is a typo on the build script so that the necessary library is not coiped.
https://github.com/norihiro/obs-face-tracker/blob/2b6548f09f0b3d2693d5d222a08e8aa284c22995/.github/workflows/main.yml#L210-L211
This script (`change-rpath.sh`) copies necessary libraries by checking dependencies using `otool -L` but I put a wrong binary path. I will fix it.
