### ISSUE TITLE
Trying to use software in a Church where the camera is 20m away

### ISSUE THREAD

**Issue by jpage386** [norihiro/obs-face-tracker#126]
Hi,
I love the plugin, but I'm trying to use it in a church setting.  The face tracking works, but it doesn't move the PTZ only moves a small amount (maybe 8m side to side).  The cameras has a much wider movement range.  Is there any way to expand the field of motion so I can track properly.

Also, is there any way to disable zoom and just track x & y?  I've tried setting up the Z dead and non-linear Z. (I don't see the max zoom as listed in a different issue)

Thanks

**Comment by norihiro** [comment]
> is there any way to disable zoom and just track x & y?

![max-zoom-zero](https://user-images.githubusercontent.com/780600/226143273-56e16742-60ef-434b-bebe-18d2cc553240.png)
If you set `Max control (zoom)` to 0, the zoom will not change at all.

> it doesn't move the PTZ only moves a small amount (maybe 8m side to side). The cameras has a much wider movement range.

I'm afraid this might be the limitation of your PTZ camera. It depends models. I'm mainly testing with SRG-120DH. When shooting from 20m away, the slowest speed is still not so smooth. Some other models has slower speed settings.

If that's the case, you might need to find another model or put the camera more front side. As a workaround, what I can suggest is use the pause feature when the camera is live.

**Comment by jpage386** [comment]
Hi,

Thanks for the information.  I feel like a noob here, but I didn't see that
zoom control in the face tracker menu.

As for the camera,  I can work the pan fine using the obs PTZ console. When
the face tracker tries to follow, it just stops following, and the person
goes out of frame.

Thanks

**Comment by norihiro** [comment]
> I didn't see that zoom control in the face tracker menu.

1. Please open a filter dialog of your source.
2. Select Face Tracker PTZ
3. Scroll the list of the properties

I hope you can find that property.
![Screenshot_2023-03-19_08-49-47a](https://user-images.githubusercontent.com/780600/226145931-280b6d6a-e899-4dac-aa87-b0a891032cf5.png)

**Comment by jpage386** [comment]
Thanks.

I was using the plug in under the scene, and not attached to the device.

What I'm finding strange, is when using the camera one, if I have only show
face detection results, I don't see the green box, but if I turn on the
always show, it does.

**Comment by norihiro** [comment]
> What I'm finding strange, is when using the camera one, if I have only show
> face detection results, I don't see the green box, but if I turn on the
> always show, it does.

I'm sorry that my description on the dialog was not so good.
When enabling only `Show face detection results`, the rectangle will be displayed when the source is not in Live, eg. preview, projector, or source dock.
When both `Show face detection results` and `Always show information (useful for demo)` are enabled, the rectangle will be displayed even when the source is in live.

**Comment by jpage386** [comment]
Ok, thanks. I think i have it working.  I was on obs 29, i downgraded and
it started working.  I just have to play with the values to try and get the
trackin to be smoother.  Rigt now it tracks a bit then jumps to keep in
frame.

Thanks

**Comment by norihiro** [comment]
> I wonder if there is an easy way to increase the polling interval for face detection?

Currently, it's a 2.0-second interval hard coded in the source code.

https://github.com/norihiro/obs-face-tracker/blob/ed988369ba0394422b47910d4dc0be616f1f8cd4/src/face-tracker-manager.cpp#L321

**Comment by jpage386** [comment]
Hi,
I don't know what I'm doing wrong.  I can't get this to build based on the directions on the site.  I finally got dlib to build, and now I'm getting issues about libvisca.  Can you let me know what source you used for libvisca?  At this point I'm willing to pay to have someone compile this with a 1 second poll and provide the dll.

**Comment by norihiro** [comment]
The `libvisca` is pointing to `https://github.com/norihiro/libvisca-ip.git`.
You can pull `libvisca` and `dlib` by a command `git submodule update --init`. I'm sorry that the instruction on `README.md` was not up to date.

Alternatively, if you are changing very small amount, you can just push to your branch with a change below so that GitHub Actions will run the build flow.

```patch
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index adee83c..dcdc39e 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,7 +5,7 @@ on:
     paths-ignore:
       - '**.md'
     branches:
-      - main
+      - '*'
     tags:
       - '*'
   pull_request:
```

**Comment by jpage386** [comment]
Hi,  I did as you suggested and just downloaded and tried to compile it with no modifications.
I had to use the following to get cmake to complete without major errors
cmake ^
-Dlibobs_DIR="%OBSPath%\build64\libobs" ^
-Dlibobs_INCLUDE_DIR="%OBSPath%\libobs" ^
-Dlibobs_LIB="%OBSPath%\build64\libobs\%build_config%\obs.lib" ^
-Dw32-pthreads_DIR="%OBSPath%\build64\deps\w32-pthreads" ^
-Dw32-pthreads_LIB="%OBSPath%\build64\deps\w32-pthreads\%build_config%\w32-pthreads.lib" ^
-Dobs-frontend-api_DIR="%OBSPath%\build64\UI\obs-frontend-api" ^
-DQt5_DIR="%OBSPath%\..\obs-build-dependencies\windows-deps-qt5-2023-04-12-x64\lib\cmake\Qt5" ^
-DOBS_FRONTEND_LIB="%OBSPath%\build64\UI\obs-frontend-api\%build_config%\obs-frontend-api.lib" ..
make
The problem is, Cmake throws this message:
CMake Warning (dev) in libvisca/visca/CMakeLists.txt:
  AUTOGEN: No valid Qt version found for target visca.  AUTOMOC and AUTOUIC
  disabled.  Consider adding:

    find_package(Qt<QTVERSION> COMPONENTS Widgets)

  to your CMakeLists.txt file.
if I try to compile what cmake created, I get:
\obs-face-tracker\libvisca\visca\libvisca.c(58,17): error C2065: 'stderr': undeclared identifier [\obs-face-tracker\build\libvisca\visca\visca.vcxproj]
\obs-face-tracker\libvisca\visca\libvisca.c(59,17): error C2065: 'stderr': undeclared identifier [\obs-face-tracker\build\libvisca\visca\visca.vcxproj]

I'm not 100% on your git comment, as I'm new to GitHub.

Jon

**Comment by norihiro** [comment]
It's a little weird. Qt6 should be linked and Qt5 is not necessary.

If I remember correctly, OBS 28 and later will reject plugins that link Qt5.

If it does not work, you can download from this site. I set 0.5 second in another branch.
- Branch: https://github.com/norihiro/obs-face-tracker/tree/fast-detection.
- Build summary: https://github.com/norihiro/obs-face-tracker/actions/runs/4889366215 (please scroll to the bottom.)

**Comment by jpage386** [comment]
Thanks for all the assistance, I'm a bit of a GitNoob, so I wasn't sure what you meant above.  I've created a fork and made the changes you recommended, and it compiles wonderfully.

Thanks for all the help
Jon
