### ISSUE TITLE
I hope the face will be centered in the screen, even including the size after cropping. 

### ISSUE THREAD

**Issue by iesvme** [norihiro/obs-face-tracker#13]
I hope the face will be centered in the screen, even including the size after cropping.
Amazing OBS Plugin! Thank you for your development!

**Comment by norihiro** [comment]
Could you explain your usage briefly?

What in my mind is a scenario like this; camera has 16:9 aspect, tracking a face, and final image is 4:3 (possibly P-in-P).
In that case, I'd like to propose adding a property to define aspect ratio for the cropped area.

**Comment by iesvme** [comment]
I mean like this:
No matter how I crop, the face would always centered.
![image](https://user-images.githubusercontent.com/16969250/121790874-a1278280-cc16-11eb-9f36-4ae293274264.png)

**Comment by norihiro** [comment]
It looks the frame is cropped by scene-item.
Since OBS Studio is well structured, the plugin didn't catch how the frame is cropped by scene-item, which is done at the later phase after the effect-filters.

**Comment by iesvme** [comment]
Thank you for your reply.

**Comment by norihiro** [comment]
I'm going to add a property `aspect` so that user is not required to adjust crop on the transform dialog or alt+drag.
