### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by TheTaraStark** [norihiro/obs-face-tracker#136]
**Source/filter types**
- [ ] Face Tracker (source)
- [ ] Face Tracker (filter)
- [ ] Face Tracker PTZ (a filter to control PTZ camera)
- [x] Face Tracker Monitor

**Describe your problem**
It looks like a monitor was installed in my control bar that allows for various camera effects, and alters the close/minimize functions of MacOS windows, but I did not need or ask for those. I would like to get rid of that monitor and other components that don't live inside OBS, but I cannot find the files the package installer created to delete them. Where would I find these?

Thanks!

**Desktop**
 - Hardware: M1 Macbook Air
 - OS: MacOS 14.0
 - OBS Version: 29.1.3
 - Face Tracker Version: 0.7.1

**Comment by norihiro** [comment]
I'm sorry that all sources and filters are put together into one binary file. This is because a lot of code is shared each other. So you cannot uninstall partially, for now.

I will consider options to hide these sources.

**Comment by TheTaraStark** [comment]
To be clear, this is the "monitor" I was talking about. It's persistent in the Mac menu bar even when OBS is closed, and seems to also affect every app OBS captures (even so far as to change their name, breaking scripts I once used while streaming).
<img width="249" alt="Screenshot 2023-10-02 at 11 42 59 AM" src="https://github.com/norihiro/obs-face-tracker/assets/84986402/f45de7e5-404d-4c0c-a5c1-f970e91e4309">

Is there an "uninstall all" option?

**Comment by norihiro** [comment]
> <img alt="Screenshot 2023-10-02 at 11 42 59 AM" width="249" src="https://user-images.githubusercontent.com/84986402/272018328-f45de7e5-404d-4c0c-a5c1-f970e91e4309.png">

I'm sorry that I don't know what this icon is. The plugin is just running inside OBS and there should not be anything else outside OBS.
What will happen if you click the icon or interact with the icon?

The monitor provided by obs-face-tracker is a dock window like below, that can be added from OBS's `Tools` menu.
![obs-face-tracker-monitor](https://github.com/norihiro/obs-face-tracker/assets/780600/3929bee5-a32c-485b-89d6-835918087aae)

**Comment by TheTaraStark** [comment]
I'm feeling quite silly - did some digging to see if any other software had been installed just before or after, saw an Apple update, and it turns out the icon I highlighted is part of a feature that comes built-in to Mac OS 14, which I had just upgraded to around the same time. Thanks for bearing with me!
