### ISSUE TITLE
Cannot figure out how to remove old docks

### ISSUE THREAD

**Issue by nospam2k** [norihiro/obs-face-tracker#138]
I must be missing something. In the tools menu is an option to add FT Dock, but I can't find a way to remove it from the Docks tab.

**Comment by norihiro** [comment]
The dock should be removed by clicking `x` button on the top right corner of the dock.

If you have locked the docks, you need to click `Docks` in the menu, uncheck `Lock Docks`, then click the `x` button.

**Comment by nospam2k** [comment]
The lock docks was what I was missing. Thx!
