### ISSUE TITLE
Bug de lancement OBS Studio 30.1.2

### ISSUE THREAD

**Issue by GGUILMET** [norihiro/obs-face-tracker#152]
**Source/filter types**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Desktop (please complete the following information):**
 - OS: [Windows 11 ]
 - OBS Version: [30.1.2]
 - Face Tracker Version: [0.7.1]

**Additional context**

![bug-obs-face-tracker-0 7 1-obs27-Windows](https://github.com/norihiro/obs-face-tracker/assets/30655327/24be5def-2286-4cb6-832c-66cc828ffb28)
![windows 11](https://github.com/norihiro/obs-face-tracker/assets/30655327/2a9fcd72-df86-4d7c-b019-f1e6e559a79e)

**Comment by GGUILMET** [comment]
Bonjour, j'ai réinstaller le plugin et sa refonctionne normalement. Vous pouvez fermé le ticket
Cordialement. 
Hello, I reinstalled the plugin and it works normally again. You can close the ticket
Sincerely.

**Comment by norihiro** [comment]
I'm happy to hear that your issue was resolved.
I guess the error could be made if the user downloaded the plugin for OBS Studio 27.
