### ISSUE TITLE
Install on Fedora

### ISSUE THREAD

**Issue by taynotfound** [norihiro/obs-face-tracker#153]
Hey, i'd like to install this on fedora, yet fedora doesnt use .deb it uses .rpm. Is there a way to make a .rpm?

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - OBS Version: 30.1.1

**Comment by norihiro** [comment]
Yes, there is a way to make an RPM file.
My other plugins such as [obs-color-monitor](https://github.com/norihiro/obs-color-monitor/) have the flow to make the RPM package so you can follow the command sequence.
I'm adding the RPM package flow one by one. I will release the RPM file for this plugin if it's prepared.

**Comment by taynotfound** [comment]
That would be great, thanks!Message ID:
***@***.***>

>
