### ISSUE TITLE
Face Tracker starts from the initial condition when transit to Program

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-face-tracker#17]
Conditions
- `Duplicate Sources` and `Duplicate Scene` are both enabled.
- Face Tracker is added to a Group, which contains a camera or video source.

Since the internal state of Face Tracker is not copied, Face Tracker start from the initial location.
I found this issue when looking into #14 but this is a different issue originally reported.

**Comment by iesvme** [comment]
It works very well in 0.1.1 now. Thank you so so much!!!
