### ISSUE TITLE
Preset for parameters

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-face-tracker#18]
This is a feature request to have a preset of parameters.
## Motivation
- Some parameters are difficult to adjust
- There is a need to change parameters to make a dynamic move

##  Consideration
- Maybe the preset can change `track_x/y/z`, `scale_max`, and PID control parameters at once. Or, should I separate PID?
- The preset can be added by user as well.
- Assigning to hotkeys would be useful.

**Comment by iesvme** [comment]
Looks great! Expecting improvements! More and more people will like your amazing plugin!
