### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by Alvazz** [norihiro/obs-face-tracker#2]
Can you provide a smoother description of the win 10 compilation process? It seems a bit tricky. Thank you.

**Comment by Alvazz** [comment]
![error](https://user-images.githubusercontent.com/50744096/119840821-e4f06b80-bf37-11eb-90b4-333b5f45256a.png)

**Comment by norihiro** [comment]
I think you need to specify cmake options `-DLIBOBS_LIB` as well for Windows.

I just now succeeded to build this on Windows (#1) on Azure Pipelines. I've not tested it on Windows yet.
See `ci/windows/prepare-windows.cmd` for full cmake options.
Whole build flow is written in `azure-pipelines.yml`.

In my build flow, files should be extracted like below.
```
working-directory
|- obs-studio (from git)
  |- libobs
  |- UI
  ...
`- obs-face-tracker (from git)
  |- src
  `- dlib (from git)
    `- dlib
      `- image_processing
        ...
```
