### ISSUE TITLE
Filter does to appear with deb install on Mint 20.1

### ISSUE THREAD

**Issue by Pedulla** [norihiro/obs-face-tracker#22]
OBS 27.01 installed on Mint 20.01 (Mate)

deb install puts .so in: /usr/lib/x86_64-linux-gnu/obs-plugins/obs-face-tracker.so
Needed to add link to the rest of the plugins for it to appear in OBS.

sudo ln -s /usr/lib/x86_64-linux-gnu/obs-plugins/obs-face-tracker.so /usr/lib/obs-plugins/

**Comment by norihiro** [comment]
Thank you for reporting. The same bugs are there in my other plugins but I have never noticed it.

**Comment by Pedulla** [comment]
Thank you!
