### ISSUE TITLE
FEATURE REQUEST: PTZ VISCA (or other) Control

### ISSUE THREAD

**Issue by Mazecreator** [norihiro/obs-face-tracker#23]
Hi,

Great plugin detecting the face, it would be nice if rather than a zoomed out and digital zoom to the area of interest that the software would control a PTZ Camera to track and optimize the image resolution.

That is, the PTZ control would move the camera left/right/up/down and zoom in or out to help maximize the persons face.

Certainly it would be nice to extend this to bodies as people might not be facing the camera and if there are multiple bodies to include as many as possible.

Thanks for the work on this!

**Comment by norihiro** [comment]
I'm thinking referring to [obs-ptz](https://github.com/glikely/obs-ptz) would be a good start for me to implement it.
I'm appreciate if someone can sponsor a camera with VISCA over IP. Old one should be enough for debugging and testing.

**Comment by Mazecreator** [comment]
> I'm thinking referring to [obs-ptz](https://github.com/glikely/obs-ptz) would be a good start for me to implement it.
> I'm appreciate if someone can sponsor a camera with VISCA over IP. Old one should be enough for debugging and testing.

I have contacted you on FaceBook..
