### ISSUE TITLE
Compilation failed on Win64

### ISSUE THREAD

**Issue by Alvazz** [norihiro/obs-face-tracker#3]
Thanks for the author's update, I followed your updated compilation guide, generated the sln project under win10 64 bit, compile it, and encountered some errors. Please check it out!

![error1](https://user-images.githubusercontent.com/50744096/119874497-40325600-bf58-11eb-9dee-29e7bae3a7b5.png)
![error2](https://user-images.githubusercontent.com/50744096/119874534-47f1fa80-bf58-11eb-9754-12f71fb1add3.png)
![error3](https://user-images.githubusercontent.com/50744096/119874540-4b858180-bf58-11eb-8c47-942156d627e6.png)

**Comment by norihiro** [comment]
The issue was fixed at commit 55aabf83156. Could you pull the latest code?
