### ISSUE TITLE
Bugs out when user is away

### ISSUE THREAD

**Issue by saraprc-dev** [norihiro/obs-face-tracker#37]
It just zooms in on where it last tracked my face and doesn't track when I come back. "Reset Tracking" doesn't work, the only solution is to delete filter and add it again, which resets the preferences set.

**Comment by norihiro** [comment]
A log file is required to investigate your issue. Please post a link to your current log file.
If you can reproduce the issue, please reproduce it and send the log. Even if you cannot reproduce the issue, the log file would be helpful.
1. In OBS select Help > Log Files > Upload Current Log File.
2. Click Copy URL and then paste the link here.
Just in case you mind to post it, please let me know these information; OS, OBS version, plugin version.
