### ISSUE TITLE
Not showing up in filters list.

### ISSUE THREAD

**Issue by PixelRave** [norihiro/obs-face-tracker#40]
Hello I have installed this plugin on both of my PCs but it will not show up in the filters list, Is there something I am missing?

Error log shows noting is wrong.

Windows 10

Latest OBS

**Comment by norihiro** [comment]
A current log file is required to help fix your issue. Please post a link to your current log file.

- In OBS select Help > Log Files > Upload Current Log File.
- Click *Copy URL* and then paste the link here.

<img src='https://cdn.discordapp.com/attachments/376042662580715521/768461567347261470/unknown.png'/>

**Comment by PixelRave** [comment]
> 
> 
> A current log file is required to help fix your issue. Please post a link to your current log file.
> 
>     * In OBS select Help > Log Files > Upload Current Log File.
> 
>     * Click _Copy URL_ and then paste the link here.
> 
> 
> ![](https://camo.githubusercontent.com/a338dbdc59dc6aa8650d30679e5251cffc20555a3524709df890ddc8e5f81e65/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3337363034323636323538303731353532312f3736383436313536373334373236313437302f756e6b6e6f776e2e706e67)

https://obsproject.com/logs/fo4-zu1ogRsRVKB5

**Comment by norihiro** [comment]
`obs-face-tracker.dll` is not shown in the list of `Loaded Modules:`.
Would you ensure the plugin is installed at the correct location?
If installing from zip file, two folders `obs-plugins` and `data` should be drag-dropped into the `obs-studio` directory, which already contains these directories.

**Comment by norihiro** [comment]
I have uploaded the wrong zip file to the release page. Please re-download from the release page.
https://github.com/norihiro/obs-face-tracker/releases

The wrong file was `obs-audio-pan-filter`. Please remove it if you don't need it.
- If you have installed it using the installer, I think the uninstaller is available.
- If you have unzipped, please remove these files (1 directory and 4 files).
  data/obs-plugins/obs-audio-pan-filter/
  obs-plugins/32bit/obs-audio-pan-filter.dll
  obs-plugins/32bit/obs-audio-pan-filter.pdb
  obs-plugins/64bit/obs-audio-pan-filter.dll
  obs-plugins/64bit/obs-audio-pan-filter.pdb

I'm sorry for your inconvenience.
If you have further issue related to this, feel free to reopen this ticket.

**Comment by PixelRave** [comment]
> 
> 
> I have uploaded the wrong zip file to the release page. Please re-download from the release page.
> https://github.com/norihiro/obs-face-tracker/releases
> 
> The wrong file was `obs-audio-pan-filter`. Please remove it if you don't need it.
> 
>     * If you have installed it using the installer, I think the uninstaller is available.
> 
>     * If you have unzipped, please remove these files (1 directory and 4 files).
>       data/obs-plugins/obs-audio-pan-filter/
>       obs-plugins/32bit/obs-audio-pan-filter.dll
>       obs-plugins/32bit/obs-audio-pan-filter.pdb
>       obs-plugins/64bit/obs-audio-pan-filter.dll
>       obs-plugins/64bit/obs-audio-pan-filter.pdb
> 
> 
> I'm sorry for your inconvenience.
> If you have further issue related to this, feel free to reopen this ticket.

Ok thank you for fixing the issue
