### ISSUE TITLE
Plug in does not appear in filters list.

### ISSUE THREAD

**Issue by dfandrews** [norihiro/obs-face-tracker#42]
May not be supported but I'm running Monterey on a MBP M1.  Everything looks good as far as installation goes but the plugin doesn't show up in the filters list for my camera.

**Comment by norihiro** [comment]
A current log file is required to help fix your issue. Please post a link to your current log file.
- In OBS select Help > Log Files > Upload Current Log File.
- Click Copy URL and then paste the link here.

I assume you have downloaded the official binary of OBS-Studio and it is running in Rosetta2. In that case, the plugin should work (but I have not tested that environment).

**Comment by dfandrews** [comment]
Not sure which would apply; Current or Last so included both.

https://obsproject.com/logs/IrIfP8AuqHQMd0zW <https://obsproject.com/logs/IrIfP8AuqHQMd0zW>
https://obsproject.com/logs/mYGi1T5kyK91HUTV <https://obsproject.com/logs/mYGi1T5kyK91HUTV>


Dennis

**Comment by norihiro** [comment]
Thank you for putting the log file. This is a bug in macOS packaging.
A necessary dynlib `QtNetwork` is not included in the package. I will update the package.
