### ISSUE TITLE
ptz: Implement VISCA-over-TCP

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-face-tracker#51]
- [ ] Get the response of inquiry commands for current zoom, pan and tilt.

**Comment by Mazecreator** [comment]
It may be possible to query all features of the camera as well such as Max Zoom.

Once Abs ZOOM, Pan, & Tilt can be reliably queried from the cameras, it would be good to create "Virtual Boundaries"... For example, on the right side at 45 degrees, there may be a high traffic entrance/exit that the camera could end up picking up a face and tracking. This will loose the subject it was originally tracking.  This can be used to prevent detection of "Choir" from being detected during a service as well as the camera hunts for a target.

Some future nice to haves would be "initial detection" is required in a certain volume of space.  So if there is someone at the podium and several people seated behind the podium, the algorithm can reject any matches below a certain line on the screen (or in the volume) so it only tracks the standing individual and ignores the seated individuals.  I am sure there are some great ways to detect in the volume if objects are stationary or moving (faces seated behind podium will always be near the same absolute position in the volume, where the standing speaker is likely to move, so priority would be on the moving target(s)).
