### ISSUE TITLE
ptz: Go to a preset position if face is lost

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-face-tracker#53]
If the face is lost, it should gradually zoom-out or go back to the home or the preset position.
Depends #52.

**Comment by Mazecreator** [comment]
You may want to consider "searching" as part of the return to the PreSet location.  That is, assume the user moved back towards the Preset, so start to move in that direction based upon a curve.  This might be linear over X secs or could be an Exp type of curve, one that assumes the users might still be near by and a second that assume the user rapidly headed back to the PreSet.

**Comment by wwboynton** [comment]
Simply returning to one of the pre-set positions in the obs-ptz controls would be a huge improvement by itself. Please don't feel like you need to do something fancier to justify releasing a feature like that. I sit in generally the same place and feel confident the camera will find me again if it returns home and waits for my face. This feature would be a game-changer for me.

**Comment by PoWeR-Ding** [comment]
Hi @norihiro , has this function been completed? How to operate the settings specifically?

**Comment by norihiro** [comment]
> has this function been completed?

I have not implemented the feature yet.

**Comment by wwboynton** [comment]
@norihiro thank you for implementing this feature, it will be very helpful to me 🙏🏻

It seems like this has not yet been added to the most recent release. Will it be built soon, or should I set up an environment to build it myself to use it now?

Thank you so much for your hard work!

**Comment by norihiro** [comment]
Thank you for reminding me. I forgot to make the release.
