### ISSUE TITLE
New Feature: Face landmark detection

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-face-tracker#55]
- [x] Add face landmark detection.
- [x] Put textures on the face optionally. And not render the original texture optionally.
- [x] ~~If this is accurate and fast, it can replace correlation-tracker and will detect lost face earlier.~~
  - No, face landmark detection requires the bounding box accurately.

**Comment by UnrelatedWorks** [comment]
Add a sentence in the documentation which links to articles that explain how users may create their own dataset.

**Comment by norihiro** [comment]
> Add a sentence in the documentation which links to articles that explain how users may create their own dataset.

There is a link to [dlib-models](https://github.com/davisking/dlib-models) in these documents. They explain how to create the dataset.
- https://github.com/norihiro/obs-face-tracker/blob/main/doc/properties.md
- https://github.com/norihiro/obs-face-tracker/blob/main/doc/properties-ptz.md
