### ISSUE TITLE
Support For Portrait Webcam

### ISSUE THREAD

**Issue by RocksInMyDryer** [norihiro/obs-face-tracker#59]
If my webcam is on its side, with the capture rotated 90°, the Face Tracker no longer works. Is it possible to make the tracker function if the webcam is rotated?

**Comment by norihiro** [comment]
This plugin itself does not have ability to handle rotated frame.
However, you can use this plugin with these steps:
1. Put your webcam source into a scene and rotate it.
2. Put the scene created above step into another scene. Then, apply face-tracker filter to that scene.
![rotate-example](https://user-images.githubusercontent.com/780600/130733304-3b3505f6-cfbb-4278-91fc-6bee943bb742.png)

If you have further question or problem, feel free to reopen this issue.
