### ISSUE TITLE
connot load '(null)'

### ISSUE THREAD

**Issue by topjor** [norihiro/obs-face-tracker#60]
The face tracker is not working, I just compiled using the same instructions as the azure pipline for linux
(though I am using manjaro, not ubuntu)
The regular face tracking filter does not work, I tried the PTZ version for fun to just see what it does, and when enabling the detection it detects me nicely

I tried both latest main and v0.2.2

I am using a NDI capture source for my webcam

logs for the regular tracker
```
17:06:23.122: [obs-face-tracker] face_detector_base: starting the thread.
17:06:23.122: [obs-face-tracker] Cannot load '(null)' (face-tracker.effect)
```

logs for the ptz tracker
```
17:06:44.669: [obs-face-tracker] face_detector_base: starting the thread.
17:06:44.696: [obs-face-tracker] received frame format=5
```

I hope this is enough, If you need me to collect more information, please let me know

**Comment by norihiro** [comment]
```
17:06:23.122: [obs-face-tracker] Cannot load '(null)' (face-tracker.effect)
```
This error is critical. You need to put the data file `face-tracker.effect` to the correct location.
If you installed under `/usr/local`, These 3 files should exist.
```
/usr/local/share/obs/obs-plugins/obs-face-tracker/locale/en-US.ini
/usr/local/share/obs/obs-plugins/obs-face-tracker/face-tracker.effect
/usr/local/lib/obs-plugins/obs-face-tracker.so
```

**Comment by topjor** [comment]
My obs does not want to load from `/usr/local`, but installing under `/usr` as prefix works fine, I just linked them for now.

The only question left is  what build option specifies the target installation prefix? (and should that be configured when running `cmake` or `make install`?

Otherwise it works fantastic for use with my phone with NDI as a virtual camera through OBS

**Comment by norihiro** [comment]
> The only question left is what build option specifies the target installation prefix? (and should that be configured when running cmake or make install?

I am actually not so familiar with CMake. Maybe, `cmake` option `-DCMAKE_INSTALL_PREFIX=/usr` works, doesn't it?

**Comment by norihiro** [comment]
This issue was closed because it has been inactive.
