### ISSUE TITLE
Fedora 34 coudn't open libflexiblas.so.3

### ISSUE THREAD

**Issue by aquisx** [norihiro/obs-face-tracker#65]
Getting the following error with selfcompiled obs-face-tracker & obs-studio installed via flatpak

```
13:50:39.080: os_dlopen(/home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-face-tracker/bin/64bit/obs-face-tracker.so->/home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-face-tracker/bin/64bit/obs-face-tracker.so): libflexiblas.so.3: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
13:50:39.080: 
13:50:39.080: Module '/home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-face-tracker/bin/64bit/obs-face-tracker.so' not loaded

```

**Comment by norihiro** [comment]
I'm using this plugin on Fedora 34 (OBS Studio is also built by myself but should not matter) and it works.
Could you try to install `openblas-devel`?
For your reference, this is the output of `ldd obs-face-tracker.so` on my Fedora 34 environment.
[obs-face-tracker.so-ldd.txt](https://github.com/norihiro/obs-face-tracker/files/7202911/obs-face-tracker.so-ldd.txt)

Or, you might need to install `flexiblas-netlib`, which provides `libflexiblas.so.3`.

**Comment by aquisx** [comment]
I've now installed openblas-devel & flexiblas-netlib
Getting the following error:
```
15:46:37.368: os_dlopen(/home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-face-tracker/bin/64bit/obs-face-tracker.so->/home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-face-tracker/bin/64bit/obs-face-tracker.so): **libopenblas.so.0**: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
15:46:37.368: 
15:46:37.368: Module '/home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-face-tracker/bin/64bit/obs-face-tracker.so' not loaded
```
Build process:
[obs-face-tracker.so-buildlog.txt](https://github.com/norihiro/obs-face-tracker/files/7203596/obs-face-tracker.so-buildlog.txt)

LDD:
[obs-face-tracker.so-ldd.txt](https://github.com/norihiro/obs-face-tracker/files/7203607/obs-face-tracker.so-ldd.txt)

Checked that the file exists: /lib64/libopenblas.so.0

**Comment by norihiro** [comment]
I'm suspecting Flatpak is a sandbox environment so that it fails to link libraries in the system.
Maybe, I need to look into this flow. https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#distributing-plugins-on-flathub

For now, I recommend to install `obs-studio` from `rpmfusion-free-updates` or build OBS Studio as well on Fedora 34. It's not so difficult.

**Comment by aquisx** [comment]
Now I've compiled obs-studio myself and generally it works, except that the plugin does not get detected by obsstudio.
Copied obs-face-tracker.so to the following destinations:
/usr/local/lib/obs-plugins
/usr/local/lib/obs-plugins

**Comment by norihiro** [comment]
The absolute path should be `/usr/local/lib/obs-plugins/obs-face-tracker.so` or `/usr/local/lib64/obs-plugins/obs-face-tracker.so`.

**Comment by aquisx** [comment]
Tried with both paths and it doesn't work.
Other Obs Plugins (libimage-reaction) gets detected if I put it in /home/user/.config/obs-studio/plugins
`user@user-pc ~/.c/o/plugins> pwd
/home/user/.config/obs-studio/plugins

user@user-pc ~/.c/o/plugins> tree
.
├── libimage-reaction
│   ├── bin
│   │   └── 64bit
│   │       └── libimage-reaction.so
│   └── data
│       └── locale
│           ├── en-US.ini
│           └── ru-RU.ini
└── obs-face-tracker
    ├── bin
    │   └── 64bit
    │       └── obs-face-tracker.so
    └── data
        ├── face-tracker.effect
        └── locale
            └── en-US.ini

10 directories, 6 files
user@user-pc ~/.c/o/plugins> 

`
OBS Log:
`
13:20:08.717: CPU Name: AMD Ryzen 7 2700 Eight-Core Processor
13:20:08.717: CPU Speed: 3875.897MHz
13:20:08.730: Physical Cores: 8, Logical Cores: 16
13:20:08.730: Physical Memory: 32019MB Total, 5789MB Free
13:20:08.730: Kernel Version: Linux 5.13.16-200.fc34.x86_64
13:20:08.730: Distribution: Fedora 34
13:20:08.730: Session Type: x11
13:20:08.730: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
13:20:08.732: Portable mode: false
13:20:08.769: OBS 27.1.0-rc3-8-g10810d973 (linux)
13:20:08.769: ---------------------------------
13:20:08.769: ---------------------------------
13:20:08.769: audio settings reset:
13:20:08.769: 	samples per sec: 48000
13:20:08.769: 	speakers:        2
13:20:08.783: ---------------------------------
13:20:08.784: Initializing OpenGL...
13:20:08.935: Loading up OpenGL on adapter AMD Radeon RX Vega (VEGA10, DRM 3.41.0, 5.13.16-200.fc34.x86_64, LLVM 12.0.1)
13:20:08.935: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 21.1.8, shading language 4.60
13:20:08.950: ---------------------------------
13:20:08.950: video settings reset:
13:20:08.950: 	base resolution:   1920x1080
13:20:08.950: 	output resolution: 1280x720
13:20:08.950: 	downscale filter:  Bicubic
13:20:08.950: 	fps:               60/1
13:20:08.950: 	format:            NV12
13:20:08.950: 	YUV mode:          709/Partial
13:20:08.950: NV12 texture support not available
13:20:08.952: Audio monitoring device:
13:20:08.952: 	name: Standard
13:20:08.952: 	id: default
13:20:08.952: ---------------------------------
13:20:08.958: Failed to load 'en-US' text for module: 'decklink-captions.so'
13:20:08.963: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
13:20:09.057: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
13:20:09.057: No blackmagic support
13:20:09.072: [obs-browser]: Version 2.16.1
13:20:09.072: [obs-browser]: CEF Version 87.1.12+g03f9336+chromium-87.0.4280.88
13:20:09.088: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
13:20:09.088: 
13:20:09.088: FFMPEG VAAPI supported
13:20:09.125: VLC found, VLC video source enabled
13:20:09.129: Failed to load 'de-DE' text for module: 'libimage-reaction.so'
13:20:09.161: ---------------------------------
13:20:09.161:   Loaded Modules:
13:20:09.161:     libimage-reaction.so
13:20:09.161:     vlc-video.so
13:20:09.161:     text-freetype2.so
13:20:09.161:     rtmp-services.so
13:20:09.161:     obs-x264.so
13:20:09.161:     obs-vst.so
13:20:09.161:     obs-transitions.so
13:20:09.161:     obs-outputs.so
13:20:09.162:     obs-filters.so
13:20:09.162:     obs-ffmpeg.so
13:20:09.162:     obs-browser.so
13:20:09.162:     linux-v4l2.so
13:20:09.162:     linux-pulseaudio.so
13:20:09.162:     linux-decklink.so
13:20:09.162:     linux-capture.so
13:20:09.162:     image-source.so
13:20:09.162:     frontend-tools.so
13:20:09.162:     decklink-ouput-ui.so
13:20:09.162:     decklink-captions.so
13:20:09.162: ---------------------------------
13:20:09.162: ==== Startup complete ===============================================
13:20:09.165: All scene data cleared
13:20:09.165: ------------------------------------------------
13:20:09.175: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.36) 15.0.0'
13:20:09.175: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
13:20:09.175: pulse-input: Started recording from 'alsa_output.usb-Plantronics_Plantronics_Savi_7xx_C33C136D34AB47498B98D76C4A031302-00.mono-fallback.monitor'
13:20:09.176: [Loaded global audio device]: 'Desktop-Audio'
13:20:09.176: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.36) 15.0.0'
13:20:09.177: pulse-input: Audio format: s16le, 16000 Hz, 1 channels
13:20:09.177: pulse-input: Started recording from 'alsa_input.usb-Plantronics_Plantronics_Savi_7xx_C33C136D34AB47498B98D76C4A031302-00.mono-fallback'
13:20:09.177: [Loaded global audio device]: 'Mikrofon-/AUX-Audio'
13:20:09.177: v4l2-input: Start capture from /dev/video0
13:20:09.273: v4l2-input: Input: 0
13:20:09.328: v4l2-input: Resolution: 1280x720
13:20:09.329: v4l2-input: Pixelformat: YUYV
13:20:09.329: v4l2-input: Linesize: 2560 Bytes
13:20:09.329: v4l2-input: Framerate: 10.00 fps
13:20:09.330: v4l2-input: /dev/video0: select timeout set to 500000us (5x frame periods)
13:20:09.331: Switched to scene 'Szene'
13:20:09.331: ------------------------------------------------
13:20:09.332: Loaded scenes:
13:20:09.332: - scene 'Szene':
13:20:09.332:     - source: 'Webcam' (v4l2_input)
13:20:09.332: ------------------------------------------------
13:20:09.719: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop-Audio)
13:20:09.719: 
13:20:09.857: v4l2-input: /dev/video0: select timed out
13:20:09.857: v4l2-input: /dev/video0: failed to log status
13:20:10.358: v4l2-input: /dev/video0: select timed out
13:20:10.358: v4l2-input: /dev/video0: failed to log status
13:23:34.214: ==== Shutting down ==================================================
13:23:34.379: v4l2-input: /dev/video0: Stopped capture after 1020 frames
13:23:34.412: pulse-input: Stopped recording from 'alsa_output.usb-Plantronics_Plantronics_Savi_7xx_C33C136D34AB47498B98D76C4A031302-00.mono-fallback.monitor'
13:23:34.413: pulse-input: Got 76940 packets with 9849856 frames
13:23:34.413: pulse-input: Stopped recording from 'alsa_input.usb-Plantronics_Plantronics_Savi_7xx_C33C136D34AB47498B98D76C4A031302-00.mono-fallback'
13:23:34.413: pulse-input: Got 9615 packets with 3278688 frames
13:23:34.414: All scene data cleared
13:23:34.414: ------------------------------------------------
13:23:34.419: Failed to fetch parent window geometry!
13:23:34.419: Failed to fetch parent window geometry!
13:23:34.419: Failed to fetch parent window geometry!
13:23:34.419: Failed to fetch parent window geometry!
13:23:34.478: [Scripting] Total detached callbacks: 0
13:23:34.478: Freeing OBS context data
13:23:34.494: == Profiler Results =============================
13:23:34.494: run_program_init: 894.083 ms
13:23:34.494:  ┣OBSApp::AppInit: 2.809 ms
13:23:34.494:  ┃ ┗OBSApp::InitLocale: 1.547 ms
13:23:34.494:  ┗OBSApp::OBSInit: 769.79 ms
13:23:34.494:    ┣obs_startup: 27.6 ms
13:23:34.494:    ┗OBSBasic::OBSInit: 704.988 ms
13:23:34.495:      ┣OBSBasic::InitBasicConfig: 0.077 ms
13:23:34.495:      ┣OBSBasic::ResetAudio: 0.155 ms
13:23:34.495:      ┣OBSBasic::ResetVideo: 182.524 ms
13:23:34.495:      ┣OBSBasic::InitOBSCallbacks: 0.02 ms
13:23:34.495:      ┣OBSBasic::InitHotkeys: 0.053 ms
13:23:34.495:      ┣obs_load_all_modules: 209.11 ms
13:23:34.495:      ┃ ┣obs_init_module(decklink-captions.so): 0.059 ms
13:23:34.495:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 0.636 ms
13:23:34.495:      ┃ ┣obs_init_module(frontend-tools.so): 48.851 ms
13:23:34.495:      ┃ ┣obs_init_module(image-source.so): 0.007 ms
13:23:34.495:      ┃ ┣obs_init_module(linux-capture.so): 0.323 ms
13:23:34.495:      ┃ ┣obs_init_module(linux-decklink.so): 0.17 ms
13:23:34.495:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0.007 ms
13:23:34.495:      ┃ ┣obs_init_module(linux-v4l2.so): 0.134 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-browser.so): 0.046 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.309 ms
13:23:34.495:      ┃ ┃ ┗nvenc_check: 0.288 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-filters.so): 0.025 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-outputs.so): 0.002 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-transitions.so): 0.007 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-vst.so): 0.002 ms
13:23:34.495:      ┃ ┣obs_init_module(obs-x264.so): 0.001 ms
13:23:34.495:      ┃ ┣obs_init_module(rtmp-services.so): 0.648 ms
13:23:34.495:      ┃ ┣obs_init_module(text-freetype2.so): 0.008 ms
13:23:34.495:      ┃ ┣obs_init_module(vlc-video.so): 2.644 ms
13:23:34.495:      ┃ ┗obs_init_module(libimage-reaction.so): 0.003 ms
13:23:34.495:      ┣OBSBasic::ResetOutputs: 0.157 ms
13:23:34.495:      ┣OBSBasic::CreateHotkeys: 0.036 ms
13:23:34.495:      ┣OBSBasic::InitService: 1.325 ms
13:23:34.495:      ┣OBSBasic::InitPrimitives: 0.099 ms
13:23:34.495:      ┗OBSBasic::Load: 171.223 ms
13:23:34.495: obs_hotkey_thread(25 ms): min=0.063 ms, median=0.167 ms, max=20.001 ms, 99th percentile=9.817 ms, 100% below 25 ms
13:23:34.495: audio_thread(Audio): min=0 ms, median=0.053 ms, max=0.703 ms, 99th percentile=0.1 ms
13:23:34.495: obs_graphics_thread(16,6667 ms): min=0.079 ms, median=0.661 ms, max=145.853 ms, 99th percentile=15.39 ms, 99.2614% below 16.667 ms
13:23:34.495:  ┣tick_sources: min=0 ms, median=0.008 ms, max=145.578 ms, 99th percentile=0.02 ms
13:23:34.495:  ┣output_frame: min=0.056 ms, median=0.174 ms, max=5.175 ms, 99th percentile=0.605 ms
13:23:34.495:  ┃ ┗gs_context(video->graphics): min=0.056 ms, median=0.174 ms, max=5.175 ms, 99th percentile=0.605 ms
13:23:34.495:  ┃   ┣render_video: min=0.007 ms, median=0.075 ms, max=2.043 ms, 99th percentile=0.456 ms
13:23:34.495:  ┃   ┃ ┗render_main_texture: min=0.006 ms, median=0.071 ms, max=2.04 ms, 99th percentile=0.451 ms
13:23:34.495:  ┃   ┗gs_flush: min=0.025 ms, median=0.086 ms, max=4.735 ms, 99th percentile=0.155 ms
13:23:34.495:  ┗render_displays: min=0.002 ms, median=0.409 ms, max=32.146 ms, 99th percentile=15.027 ms
13:23:34.495: =================================================
13:23:34.495: == Profiler Time Between Calls ==================
13:23:34.495: obs_hotkey_thread(25 ms): min=25.116 ms, median=25.235 ms, max=45.069 ms, 91.767% within ±2% of 25 ms (0% lower, 8.23296% higher)
13:23:34.495: obs_graphics_thread(16,6667 ms): min=4.132 ms, median=16.667 ms, max=145.861 ms, 98.6688% within ±2% of 16.667 ms (0.665584% lower, 0.665584% higher)
13:23:34.495: =================================================
13:23:34.511: Number of memory leaks: 0
`

**Comment by norihiro** [comment]
I tried it but I cannot reproduce the issue.
I removed `obs-face-tracker.so` from my install path and put them as same as your `tree` information as below. Then booted obs-studio. I saw `obs-face-tracker.so` is loaded.
```
$ cd ~/.config/obs-studio/plugins/
$ LANG=C tree | cat
.
`-- obs-face-tracker
    |-- bin
    |   `-- 64bit
    |       `-- obs-face-tracker.so
    `-- data
        `-- face-tracker.effect
```
If there is an issue when loading the shared object file, message should be left on the log. How about your SELinux setting?

**Comment by aquisx** [comment]
SELinux is disabled on my system
During the build process of obs-face-tracker there appears some error so rebuilding is no longer possible
[CMakeError.log](https://github.com/norihiro/obs-face-tracker/files/7234325/CMakeError.log)
[CMakeOutput.log](https://github.com/norihiro/obs-face-tracker/files/7234326/CMakeOutput.log)

**Comment by norihiro** [comment]
I'm comparing your log and my log but I couldn't identified any doubtful difference that causes failure.
[CMakeError.log](https://github.com/norihiro/obs-face-tracker/files/7236953/CMakeError.log)
[CMakeOutput.log](https://github.com/norihiro/obs-face-tracker/files/7236955/CMakeOutput.log)

If you are seeing this error, you can just ignore it.
```
  Cannot find source file:
    obs-ptz/ptz-visca.cpp
```

**Comment by aquisx** [comment]
From my sight of view eventually:
```
CMake Error at CMakeLists.txt:36 (add_subdirectory):
  add_subdirectory given source "libvisca/visca" which is not an existing
  directory.
```
or 
```
-- Checking for module 'cblas'
--   Package 'cblas', required by 'virtual:world', not found
-- Checking for module 'lapack'
--   Package 'lapack', required by 'virtual:world', not found
```

is causing that there is no make file to use.

**Comment by norihiro** [comment]
> add_subdirectory given source "libvisca/visca" which is not an existing

I recently added a submodule. Would you run this command to clone `libvisca` as a submodule?
```
git submodule update --init
```

**Comment by aquisx** [comment]
Plugin is compiled and working now.
Thanks for the advice!
