### ISSUE TITLE
(hover) wiki for attributes

### ISSUE THREAD

**Issue by Fred-DTV** [norihiro/obs-face-tracker#80]
Hi @norihiro ,

Thanks for the great plugin!
Played around with it for the first time today and it was  a lot of fun and we will use it a lot in the future.

What I couldn't find is a basic explanation what each attribute or setting actually does?
A couple are explained in the wiki but not all of them.

The best way would be little hover infos next to the settings, but of course a basic web page would do the trick too.

Thanks again for your work!

**Comment by norihiro** [comment]
You can find description of each parameter in this document.
- https://github.com/norihiro/obs-face-tracker/blob/main/doc/properties.md
- https://github.com/norihiro/obs-face-tracker/blob/main/doc/properties-ptz.md

In future, I will create a little more details of feed back parameters for PID control.

**Comment by DachsbauTV** [comment]
Ah great, didn't see those. Thanks a lot.
