### ISSUE TITLE
Cant create a Face Tracker PTZ on StreamFX source Mirror

### ISSUE THREAD

**Issue by LighthouseMedia** [norihiro/obs-face-tracker#81]
It gives the option to create a facetracker ptz under the audio tab in filters but when ever you click on it nothing happens.

**Comment by norihiro** [comment]
`Face Tracker PTZ` requires an async source such as Media Source, NDI Source. This is because the frame data is taken from CPU-side memory instead of GPU's memory.
`Source Mirror` copies frame in GPU so that it does not provide video filter.
