### ISSUE TITLE
Installation Images Download

### ISSUE THREAD

**Issue by ahorseman** [norihiro/obs-face-tracker#87]
Hello,

sorry if I ask a totally stupid question, but for the hell I cannot find the download files for obs-face-tracker. I wanted to install it on macOS according to the Wiki instructions, but I have no idea where to get the dmg from.

Could you please point out, where the files reside?

Thanks a lot.

**Comment by norihiro** [comment]
The DMG file is found in *Assets* section in the [release page](https://github.com/norihiro/obs-face-tracker/releases/).
Direct link for 0.4.2 is here.
https://github.com/norihiro/obs-face-tracker/releases/download/0.4.2/obs-face-tracker-0.4.2-macos.dmg
