### ISSUE TITLE
It will crash when creating Face Tracker source

### ISSUE THREAD

**Issue by iesvme** [norihiro/obs-face-tracker#89]
System: Win10x64 1809
OBS: 27.1.3
Face Tracker: 0.5.2
![动画](https://user-images.githubusercontent.com/16969250/147033654-f6304e11-f640-4aa6-8f3e-e79e9c7ef29c.gif)

**Comment by norihiro** [comment]
A log file is required to help fix your issue. Please post a link to your last log file.

1.    In OBS select Help > Log Files > Upload Last Log File.
2.    Copy the URL and paste it here.

**Comment by iesvme** [comment]
https://obsproject.com/logs/Epm534SPgnODh0rr

**Comment by norihiro** [comment]
The bug was identified and will be fixed in upcoming release.
