### ISSUE TITLE
Build package for macOS ARM64 (M1 processor)

### ISSUE THREAD

**Issue by hiteq** [norihiro/obs-face-tracker#90]
Hi. I'm just a fan of obs-face-tracker.
Here is the most likely branch of OBS for Apple silicon and obs-face-tracker doesn't work because of architecture maybe.
https://github.com/obsproject/obs-studio/pull/5155

I hope it work with this project someday.
![image](https://user-images.githubusercontent.com/5396900/147376573-7c09fded-0bc4-4fd9-a1f5-5642b5251685.png)

**Comment by norihiro** [comment]
A current log file is required to help fix your issue. Please post a link to your current log file.
1. In OBS select Help > Log Files > Upload Current Log File.
2. Click Copy URL and then paste the link here.

If you are running OBS Studio built for M1 architecture, I think you should build this plugin for M1 architecture.
The distributing binary is built for x86_64.

**Comment by hiteq** [comment]
Here it is.
https://obsproject.com/logs/9hHHx2zhM6TINKTa

**Comment by norihiro** [comment]
The version of OBS Studio does not look the released version.
Once the PR at OBS Studio is merged and the build flow is established, I will consider to follow it. Since the PR has not been merged yet, I'm afraid the flow would be unstable.

Until then, please use x86_64 binary or build this plugin by yourself. If there is something that needs to be fixed for arm64, PRs and issues will be welcome.
The build flow should be not so difficult if you have M1 host.
After building OBS Studio, install `openblas` (run `brew install openblas`), extract the source code of this plugin at the same level as obs-studio, and finally run `ci/macos/build-macos.sh`.

**Comment by hiteq** [comment]
Thanks for comment.
I got M1 host so I tried but got some errors.


Error with codes on root of obs-studio with no obs-face-tracker folder
----

CMake Error at cmake/external/ObsPluginHelpers.cmake:27 (find_package):
  By not providing "Findlibobs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libobs", but
  CMake did not find one.

  Could not find a package configuration file provided by "libobs" with any
  of the following names:

    libobsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "libobs" to CMAKE_PREFIX_PATH or set
  "libobs_DIR" to a directory containing one of the above files.  If "libobs"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  external/FindLibObs.cmake:98 (include)
  CMakeLists.txt:20 (include)

  -----

![image](https://user-images.githubusercontent.com/5396900/147389108-097383b2-fcaa-4177-b98c-9c3bcac07966.png)

**Comment by norihiro** [comment]
The screenshot looks something strange.
The contents of obs-face-tracker should be extracted inside `obs-studio`.
I remembered I've left build-instruction in README file. https://github.com/norihiro/obs-face-tracker#building The directory structure should be same as this instruction.

**Comment by hiteq** [comment]
![image](https://user-images.githubusercontent.com/5396900/147414498-a9e6d6ca-5b3b-40ee-82d3-4db693f40548.png)
Sorry about that I'm not familiar with cmake. I tried your instruction one by one and still missed something maybe.
My "$d0" was "face-build" folder in "Download".

**Comment by norihiro** [comment]
Could you try this cmake command instead under `face-build/obs-face-tracker`?
```
cmake .. \
	-DQTDIR="/tmp/obsdeps" \
	-DLIBOBS_INCLUDE_DIR=../../obs-studio/libobs \
	-DLIBOBS_LIB=../../obs-studio/libobs \
	-DOBS_FRONTEND_LIB="$(pwd)/../../obs-studio/build/UI/obs-frontend-api/libobs-frontend-api.dylib" \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo
```

**Comment by hiteq** [comment]
Perhaps that branch I mentioned for M1 builds have changed some locations of resources for building plugins?
![image](https://user-images.githubusercontent.com/5396900/147456391-843fa00c-3d82-4828-9241-386bbf772f46.png)

This is what I have from error log after failed cmake.
[CMakeError.log](https://github.com/norihiro/obs-face-tracker/files/7779472/CMakeError.log)
[CMakeOutput.log](https://github.com/norihiro/obs-face-tracker/files/7779473/CMakeOutput.log)

**Comment by norihiro** [comment]
The cmake files in this project are just modified from the previous version of [plugin-template](https://github.com/obsproject/obs-plugintemplate).
To be honest, I don't fully understand how it is working.

Looking at the updated `ObsPluginHelpers.cmake`,
I think you need to add these options to cmake command for obs-face-tracker.
```
-D CMAKE_OSX_ARCHITECTURES=arm64 -D OBS_CODESIGN_LINKER=OFF
```

And, if you remove these lines from `obs-studio/cmake/external/ObsPluginHelpers.cmake`, what will happen?
https://github.com/obsproject/obs-studio/blob/0524d9de747fdf2a41992bab26a89732a9610494/cmake/external/ObsPluginHelpers.cmake#L22-L37

By the way, I think [the PR](https://github.com/obsproject/obs-studio/pull/5155) aims to have cross-compile for arm64 using x64 host.
If you are building on arm64, I think you don't need to have the PR, do you?

**Comment by norihiro** [comment]
I started to modify cmake files in #92. Once it's done, the build flow with the PR 5155 might run.

**Comment by hiteq** [comment]
I found some post about arm64 build for obs-face-tracker from someone's blog. These solutions could be outdated and I got errors but hope this could be help you.
[https://www.kilinbox.net/2021/02/obsarmbuild.html](https://www.kilinbox.net/2021/02/obsarmbuild.html)

**Comment by norihiro** [comment]
The master branch of obs-studio now merged the CMake overhaul. Now some bufixes are in progress in their repository.

**Comment by hiteq** [comment]
It works so fine.
