### ISSUE TITLE
Is it possible to add swap x y z options

### ISSUE THREAD

**Issue by manbubaodoe** [norihiro/obs-face-tracker#95]
Is it possible to add swap x y z option, support camera vertical installation, or directly support face recognition after image rotation.

**Comment by norihiro** [comment]
Which are you talking about `Face Tracker PTZ` or other types?
Non-PTZ can be applied to a group or scene, which have rotated camera source.
The filter for PTZ cannot applied to the rotated picture so far.

**Comment by norihiro** [comment]
Close due to inactivities.
- For `Face Tracker PTZ`, I won't implement it since most PTZ camera does not support vertical installation.
- For other types, you can rotate your source on a scene, then apply the filter or source to the scene.
