### ISSUE TITLE
obs-face-tracker-0.5.4-Windows.zip is damaged

### ISSUE THREAD

**Issue by DachsbauTV** [norihiro/obs-face-tracker#97]
Hi,

Just a quick info: Apparently the obs-face-tracker-0.5.4-Windows.zip file is damaged. I can't unzip it on my Win10 computer.

**Comment by norihiro** [comment]
Thank you for your quick information. I have uploaded a correct zip file.

**Comment by DachsbauTV** [comment]
Thanks :) Happy New Year
