### ISSUE TITLE
BUG: 0.5.4 tracking location Y doesn't work

### ISSUE THREAD

**Issue by BryanCrotaz** [norihiro/obs-face-tracker#98]
Tracking face successfully. Tracking location X moves the face within the output frame. Location Y does nothing. The face is zoomed in, so there's plenty of pixels top and bottom to use.

Trying to use in combination with a circle mask, so looking to get the face centred vertically no matter how tall the person in front of the camera.

**Comment by norihiro** [comment]
I tested with steps below and confirmed the cropping area is moving.
- Add `Face Tracker` into `Effect Filters` on a camera source.
- Sweep `Tracking target location` / `Y` from -1.0 to +1.0. (Other settings are remaining unchanged.)

Does the issue happen on the version 0.5.4 only?
If you have upgraded from older version, could you try removing the filter and add a new filter?
If your issue happens in the newly added filter, could you describe a little detailed steps to reproduce it?

**Comment by BryanCrotaz** [comment]
I've only used 0.5.4 - no upgrade took place.

- I add the face tracker, either as a filter or as a source (no difference in behaviour)
- sweep the zoom - makes the face larger or smaller in the output window
- sweep the X - moves the face left and right
- sweep the Y - nothing happens, face is at the height it was in the original source.

If the face moves left and right in the camera, the output keeps the face at the correct X position.
If the face moves up and down in the camera, the output face moves up and down

This is 100% repeatable

**Comment by BryanCrotaz** [comment]
More testing - Y tracking only works if zoom is set to 0.2 or higher. I had it set to 0.1.
